import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { emirates } from '../fonts/emirates'
import "./globals.css";

import Header from "./sections/homepage/header";
import Footer from "./sections/homepage/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pobcast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${emirates.variable} bg-beige antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
